# Generated by Django 5.2.8 on 2025-11-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('trainer', 'Trainer'), ('client', 'Client'), ('admin', 'Admin')], default='trainer', max_length=10),
        ),
    ]
